USE catalog;
INSERT INTO publishers (name) VALUES
("Pan Macmillan"),
("HarperCollins Publishers"),
("Oxford University Press"),
("Penguin Books Ltd"),
("Wordsworth Editions Ltd"),
("Transworld Publishers Ltd"),
("Hodder & Stoughton General Division"),
("Orion Publishing Co"),
("Head of Zeus"),
("Little, Brown Book Group"),
("Simon & Schuster Ltd"),
("Quercus Publishing"),
("Bonnier Books Ltd"),
("Egmont UK Ltd"),
("Ebury Publishing"),
("Pavilion Books"),
("Bloomsbury Publishing PLC"),
("Andrews McMeel Publishing"),
("John Murray General Publishing Division"),
("Headline Publishing Group"),
("Hodder & Stoughton General "),
("Canongate Books Ltd"),
("Faber & Faber"),
("Vintage");
